In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
ls

 El volumen de la unidad C es Windows
 El n£mero de serie del volumen es: 0CC3-522F

 Directorio de C:\Users\manci\Documents\python\ejercicios

01/10/2021  03:19 p. m.    <DIR>          .
01/10/2021  03:19 p. m.    <DIR>          ..
30/09/2021  08:51 p. m.    <DIR>          .ipynb_checkpoints
01/10/2021  03:19 p. m.               838 arboles de decisiones.ipynb
29/09/2021  08:05 p. m.             3,258 gender_submission.csv
11/09/2021  07:34 p. m.           166,546 Grafiacos_Matplotlib.ipynb
11/09/2021  05:13 p. m.           259,259 graficar.ipynb
30/09/2021  08:44 p. m.            39,813 KNN k vecinos mas cercanos.ipynb
27/09/2021  10:17 p. m.           559,942 plotly.ipynb
27/09/2021  11:21 p. m.           131,913 regresi¢n lineal.ipynb
29/09/2021  11:38 p. m.           209,829 regresion logistica.ipynb
27/09/2021  07:36 p. m.           686,029 Seaborm.ipynb
29/09/2021  08:05 p. m.            28,629 test.csv
29/09/2021  07:56 p. m.            61,194 train.csv
27/09/2021  10:37 p. m. 

In [3]:
vinos = pd.read_csv('vino.csv')
vinos.head(5)

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [4]:
vinos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Alcohol                       178 non-null    float64
 1   Malic acid                    178 non-null    float64
 2   Ash                           178 non-null    float64
 3   Alcalinity of ash             178 non-null    float64
 4   Magnesium                     178 non-null    float64
 5   Total phenols                 178 non-null    float64
 6   Flavanoids                    178 non-null    float64
 7   Nonflavanoid phenols          178 non-null    float64
 8   Proanthocyanins               178 non-null    float64
 9   Color intensity               178 non-null    float64
 10  Hue                           178 non-null    float64
 11  OD280/OD315 of diluted wines  178 non-null    float64
 12  Proline                       178 non-null    float64
 13  Wine 

In [5]:
vinos['Wine Type'].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [6]:
vinos['Wine Type'].value_counts()

Two      71
One      59
Three    48
Name: Wine Type, dtype: int64

In [7]:
x=vinos.drop('Wine Type', axis=1)
y=vinos['Wine Type']

In [9]:
y

0        One
1        One
2        One
3        One
4        One
       ...  
173    Three
174    Three
175    Three
176    Three
177    Three
Name: Wine Type, Length: 178, dtype: object

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3)

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
arbol = DecisionTreeClassifier()

In [17]:
arbol.fit(x_train, y_train)

DecisionTreeClassifier()

In [18]:
predicciones= arbol.predict(x_test)

In [19]:
predicciones

array(['Three', 'One', 'Two', 'Two', 'Two', 'Three', 'One', 'One', 'One',
       'Two', 'Two', 'Two', 'Three', 'Three', 'One', 'Two', 'Two', 'Two',
       'One', 'One', 'One', 'Two', 'Three', 'Two', 'One', 'Two', 'Two',
       'Two', 'Two', 'Three', 'One', 'Two', 'Two', 'Three', 'Three',
       'Two', 'One', 'Three', 'Three', 'One', 'Two', 'Three', 'Three',
       'Two', 'Three', 'Two', 'One', 'Two', 'Two', 'Three', 'One', 'One',
       'Two', 'One'], dtype=object)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix

In [22]:
print(classification_report(y_test,predicciones))

              precision    recall  f1-score   support

         One       0.94      0.83      0.88        18
       Three       0.93      1.00      0.96        13
         Two       0.88      0.91      0.89        23

    accuracy                           0.91        54
   macro avg       0.91      0.92      0.91        54
weighted avg       0.91      0.91      0.91        54



In [23]:
print(confusion_matrix(y_test,predicciones))

[[15  0  3]
 [ 0 13  0]
 [ 1  1 21]]
